### ISSUE TITLE
Formatting issues when player has a prefix.

### ISSUE THREAD

**Issue by EpicnessTwo** [Ryozuki/Discordia#1]
It seems that when a player has a prefix to their name (Using PEX in my example), the raw formatting code is sent as the name. Please see the attached image:

![](https://i.imgur.com/H4rlzeT.png)

**Comment by edg-l** [comment]
Im releasing a fix, it should work theorically :)
Tell me if it doesn't please, thanks for the report

**Comment by EpicnessTwo** [comment]
Works perfectly now. Thanks for the amazing plugin!
